title: My Zettels
author:
  #name: GitHub User
  #email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Lightweight site for my notes

baseurl: "/zettel"
url: "https://cbjer.github.io"

show_excerpts: false # set to true to show excerpts on the homepage

markdown: kramdown

kramdown:
  mathjax: true

sass:
  sass_dir: _sass
  style: compressed

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # Skin
  skin: classic

  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    github:  cbjer
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Add extra folder
include:
  - _pages
  - assets

# Only want a few headers
header_pages:
  - about.md
  - _pages/index.md 

